# Site settings
title: JH programming 
header-img: img/home-bg.jpg
email: heiwais25@gmail.com
copyright_name: MyMeMine
description: "Study programming, statistics and physics to predict!"
baseurl: ""
url: "https://heiwais25.github.io/"
# twitter_username: SBootstrap
github_username:  heiwais25
facebook_username:  jonghyun kim
email_username:  heiwais25

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-105673303-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins : [jekyll-paginate, jekyll-feed, jekyll, jekyll-gist, mm-jekyll-prism]

# If you don't want to show disqus, add "comments:false"
disqus: heiwais25-github-blog

